src/blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path('blog/', views.blog, name="blog"),
    path('blog-detail/', views.blog_detail, name="blog_detail")
]

src/cosmetics/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include('orders.urls')),
    path('', include('accounts.urls')),
    path('', include('cart.urls')),
    path('', include('payment.urls')),
    path('', include('blog.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='initial_page'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('homepage/', views.homepage_view, name="homepage"),
    path('products/', views.products_list, name='product_list'),
    path('filter/<slug:slug>/', views.filter_by_category, name="filter_by_category"),
    path('about/', views.about, name="about"),
    path('add/wishlist/<int:product_id>/', views.add_to_wishlist, name="add_to_wishlist"),
    path('remove/wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/', views.wishlist, name="wishlist"),
    path('about/', views.about, name="about"),
    path('compare/', views.compare, name="compare"),
    path('contact/', views.contact, name="contact"),
    path('add-to-compare/<int:product_id>/', views.add_to_compare, name="add_to_compare"),
    path('remove_from_compare/<int:product_id>/', views.remove_from_compare, name="remove_from_compare"),
    path('clear_compare/', views.clear_compare, name="clear_compare")
]

src/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Post(models.Model):
    title = models.CharField(max_length=1200)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True)
    author = models.CharField(max_length=1024)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={"slug": self.slug})

    class Meta:
        db_table = 'Post'
        verbose_name = 'Post'
        verbose_name_plural = 'Post'

src/blog/views.py
from django.http import HttpResponse
from django.shortcuts import render


def blog(request):
    return render(request, "blog/blog.html")


def blog_detail(request):
    return render(request, 'blog/blog_detail.html')

src/blog/templates/blog/blog.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
  Blog
{% endblock title %}
{% block content %}
  {% include "shop/header.html" %}
  <main class="main-content">
        <!--== Start Page Header Area Wrapper ==-->
        <div class="page-header-area bg-img" data-bg-img="assets/img/photos/bg-02.jpg">
          <div class="container">
            <div class="row">
              <div class="col-12 text-center">
                <div class="page-header-content">
                  <nav class="breadcrumb-area">
                    <ul class="breadcrumb">
                      <li><a href='{% url "shop:homepage" %}'>Home</a></li>
                      <li class="breadcrumb-sep"><i class="fa fa-angle-right"></i></li>
                      <li>Blog</li>
                    </ul>
                  </nav>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!--== End Page Header Area Wrapper ==-->

        <section class="blog-area">
          <div class="container pb-80">
            <div class="row">
              <div class="col-sm-6 col-lg-4">
                <!--== Start Blog Item ==-->
                <div class="post-item">
                  <div class="inner-content mb-70 mb-md-30">
                    <div class="thumb">
                      <a href='/argima/argima/blog'><img src="assets/img/blog/01.jpg" class="img" alt="Image-HasTech"></a>
                    </div>
                    <div class="content">
                      <a class='category' href='/argima/argima/blog'>Fashion</a>
                      <h4 class="title"><a href='/argima/argima/single-blog'>This is Secound Post For XipBlog</a></h4>
                      <div class="meta">
                        <span>Posted by</span>
                        <a class='author' href='/argima/argima/blog'>Demo Posthemes</a>
                        <a class='date' href='/argima/argima/blog'>Sep 26TH, 2021</a>
                      </div>
                    </div>
                  </div>
                </div>
                <!--== End Blog Item ==-->
              </div>
              <div class="col-sm-6 col-lg-4">
                <!--== Start Blog Item ==-->
                <div class="post-item">
                  <div class="inner-content mb-70 mb-md-30">
                    <div class="thumb">
                      <a href='/argima/argima/blog'><img src="assets/img/blog/02.jpg" class="img" alt="Image-HasTech"></a>
                    </div>
                    <div class="content">
                      <a class='category' href='/argima/argima/blog'>Fashion</a>
                      <h4 class="title"><a href='/argima/argima/single-blog'>This is Third Post For XipBlog</a></h4>
                      <div class="meta">
                        <span>Posted by</span>
                        <a class='author' href='/argima/argima/blog'>Demo Posthemes</a>
                        <a class='date' href='/argima/argima/blog'>Sep 26TH, 2021</a>
                      </div>
                    </div>
                  </div>
                </div>
                <!--== End Blog Item ==-->
              </div>
              <div class="col-sm-6 col-lg-4">
                <!--== Start Blog Item ==-->
                <div class="post-item">
                  <div class="inner-content mb-70 mb-md-30">
                    <div class="thumb">
                      <a href='/argima/argima/blog'><img src="assets/img/blog/03.jpg" class="img" alt="Image-HasTech"></a>
                    </div>
                    <div class="content">
                      <a class='category' href='/argima/argima/blog'>Fashion</a>
                      <h4 class="title"><a href='/argima/argima/single-blog'>This is Fourth Post For XipBlog</a></h4>
                      <div class="meta">
                        <span>Posted by</span>
                        <a class='author' href='/argima/argima/blog'>Demo Posthemes</a>
                        <a class='date' href='/argima/argima/blog'>Sep 26TH, 2021</a>
                      </div>
                    </div>
                  </div>
                </div>
                <!--== End Blog Item ==-->
              </div>
              <div class="col-sm-6 col-lg-4">
                <!--== Start Blog Item ==-->
                <div class="post-item">
                  <div class="inner-content mb-70 mb-md-30">
                    <div class="thumb">
                      <a href='/argima/argima/blog'><img src="assets/img/blog/04.jpg" class="img" alt="Image-HasTech"></a>
                    </div>
                    <div class="content">
                      <a class='category' href='/argima/argima/blog'>Fashion</a>
                      <h4 class="title"><a href='/argima/argima/single-blog'>This is First Post For XipBlog</a></h4>
                      <div class="meta">
                        <span>Posted by</span>
                        <a class='author' href='/argima/argima/blog'>Demo Posthemes</a>
                        <a class='date' href='/argima/argima/blog'>Sep 26TH, 2021</a>
                      </div>
                    </div>
                  </div>
                </div>
                <!--== End Blog Item ==-->
              </div>
              <div class="col-sm-6 col-lg-4">
                <!--== Start Blog Item ==-->
                <div class="post-item">
                  <div class="inner-content mb-70 mb-md-30">
                    <div class="thumb">
                      <a href='/argima/argima/blog'><img src="assets/img/blog/05.jpg" class="img" alt="Image-HasTech"></a>
                    </div>
                    <div class="content">
                      <a class='category' href='/argima/argima/blog'>Fashion</a>
                      <h4 class="title"><a href='/argima/argima/single-blog'>The History and the Hype</a></h4>
                      <div class="meta">
                        <span>Posted by</span>
                        <a class='author' href='/argima/argima/blog'>Demo Posthemes</a>
                        <a class='date' href='/argima/argima/blog'>Sep 26TH, 2021</a>
                      </div>
                    </div>
                  </div>
                </div>
                <!--== End Blog Item ==-->
              </div>
              <div class="col-sm-6 col-lg-4">
                <!--== Start Blog Item ==-->
                <div class="post-item">
                  <div class="inner-content mb-70 mb-md-30">
                    <div class="thumb">
                      <a href='/argima/argima/blog'><img src="assets/img/blog/06.jpg" class="img" alt="Image-HasTech"></a>
                    </div>
                    <div class="content">
                      <a class='category' href='/argima/argima/blog'>Fashion</a>
                      <h4 class="title"><a href='/argima/argima/single-blog'>best facial cream ever</a></h4>
                      <div class="meta">
                        <span>Posted by</span>
                        <a class='author' href='/argima/argima/blog'>Demo Posthemes</a>
                        <a class='date' href='/argima/argima/blog'>Sep 26TH, 2021</a>
                      </div>
                    </div>
                  </div>
                </div>
                <!--== End Blog Item ==-->
              </div>
              <div class="col-sm-6 col-lg-4">
                <!--== Start Blog Item ==-->
                <div class="post-item">
                  <div class="inner-content">
                    <div class="thumb">
                      <a href='/argima/argima/blog'><img src="assets/img/blog/07.jpg" class="img" alt="Image-HasTech"></a>
                    </div>
                    <div class="content">
                      <a class='category' href='/argima/argima/blog'>Fashion</a>
                      <h4 class="title"><a href='/argima/argima/single-blog'>best mackup secret XipBlog</a></h4>
                      <div class="meta">
                        <span>Posted by</span>
                        <a class='author' href='/argima/argima/blog'>Demo Posthemes</a>
                        <a class='date' href='/argima/argima/blog'>Sep 26TH, 2021</a>
                      </div>
                    </div>
                  </div>
                </div>
                <!--== End Blog Item ==-->
              </div>
              <div class="col-sm-6 col-lg-4">
                <!--== Start Blog Item ==-->
                <div class="post-item">
                  <div class="inner-content">
                    <div class="thumb">
                      <a href='/argima/argima/blog'><img src="assets/img/blog/08.jpg" class="img" alt="Image-HasTech"></a>
                    </div>
                    <div class="content">
                      <a class='category' href='/argima/argima/blog'>Fashion</a>
                      <h4 class="title"><a href='/argima/argima/single-blog'>women secret beauty tips</a></h4>
                      <div class="meta">
                        <span>Posted by</span>
                        <a class='author' href='/argima/argima/blog'>Demo Posthemes</a>
                        <a class='date' href='/argima/argima/blog'>Sep 26TH, 2021</a>
                      </div>
                    </div>
                  </div>
                </div>
                <!--== End Blog Item ==-->
              </div>
              <div class="col-sm-6 col-lg-4">
                <!--== Start Blog Item ==-->
                <div class="post-item">
                  <div class="inner-content">
                    <div class="thumb">
                      <a href='/argima/argima/blog'><img src="assets/img/blog/09.jpg" class="img" alt="Image-HasTech"></a>
                    </div>
                    <div class="content">
                      <a class='category' href='/argima/argima/blog'>Fashion</a>
                      <h4 class="title"><a href='/argima/argima/single-blog'>This is First Post XipBlog</a></h4>
                      <div class="meta">
                        <span>Posted by</span>
                        <a class='author' href='/argima/argima/blog'>Demo Posthemes</a>
                        <a class='date' href='/argima/argima/blog'>Sep 26TH, 2021</a>
                      </div>
                    </div>
                  </div>
                </div>
                <!--== End Blog Item ==-->
              </div>
            </div>
          </div>
        </section>
        <!--== End Blog Area Wrapper ==-->
  </main>
{% endblock content %}