src/accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"


urlpatterns = [
    path('profile/', views.profile_details, name="profile_details"),
    path('login/', views.login_view, name='login_page'),
    path('signup/', views.signup_view, name="signup_page"),
    path('logout/', views.logout_user, name="logout_user")
]

src/blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path('blog/', views.blog, name="blog"),
    path('blog-detail/', views.blog_detail, name="blog_detail")
]

src/cosmetics/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include('orders.urls')),
    path('', include('accounts.urls')),
    path('', include('cart.urls')),
    path('', include('payment.urls')),
    path('', include('blog.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from shop.models import Product


class Profile(AbstractUser):
    username = models.CharField(unique=True, null=True, max_length=200)
    first_name = models.CharField(max_length=250, null=True)
    last_name = models.CharField(max_length=250, null=True)
    email = models.EmailField(max_length=200, null=True)
    phone_number = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.email
    
    def get_wishlist_count(self):
        return self.wishlist.count()

    class Meta:
        db_table = 'Profile'
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    USERNAME_FIELD = 'username'

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Profile


class RegistrationForm(UserCreationForm):
    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'email',
            'phone_number',
            'password1',
            'password2'
        ]

src/accounts/views.py
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from accounts.forms import RegistrationForm
from accounts.models import Profile


@login_required(login_url='accounts:login_page')
def profile_details(request):
    user = request.user
    context = {
        'user': user
    }
    return render(request, 'accounts/profile.html', context)


def login_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('shop:homepage')
        else:
            messages.info(request, "Username or Password is incorrect")
    return render(request, "accounts/login.html")


def signup_view(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone_number = request.POST.get('phone_number')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if password == confirm_password:
            user = Profile()
            user.first_name = first_name
            user.last_name = last_name
            user.username = email
            user.email = email
            user.phone_number = phone_number
            user.set_password(password)
            user.save()

            return redirect('shop:homepage')
        else:
            error_message = messages.error("Passwords do not match")
            context = {
                'error_message': error_message
            }
            return render(request, 'accounts/signup.html', context)

    return render(request, 'accounts/signup.html')


def logout_user(request):
    logout(request)
    return redirect('accounts:login_page')

src/accounts/templates/accounts/login.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
  Login Page
{% endblock title %}

{% block content %}

{% include "shop/header.html" %}
<main class="main-content">
	    <!--== Start Account Area Wrapper ==-->
		<section>
			<div class="container" data-padding-top="62"> 
			  <h4 class="fz-24 mb-25">Log in to your account</h4>
			  <div class="row">
				<div class="col-12">
				  <div class="login-form-content">
					<div class="login-form">
					  <form action="#" method="post">
						{% csrf_token %}
						<div class="form-group row">
						  <label class="col-md-3" for="frm_email">Email</label>
						  <div class="col-md-6">
							<input name="email" id="frm_email" class="form-control" type="email">
						  </div>
						</div>
						<div class="form-group row">
						  <label class="col-md-3" for="frm_pass">Password</label>
						  <div class="col-md-6">
							<div class="pass-content">
							  <input name="password" type="password" class="form-control" id="frm_pass">
							  <span class="show-pass" onclick="myFunction()">show</span>
							</div>
						  </div>
						</div>
						<div class="form-group row mb-15">
						  <div class="col-12 text-center">
							<a class="btn-forgot" href="#/">Forgot your password?</a>
							<input class="btn-save" type="submit" value="Login">
						  </div>
						</div>
					  </form>
					</div>
					<a class='btn-create-account' href='{% url "accounts:signup_page" %}'>No account? Create one here</a>
				  </div>
				</div>
			  </div>
			</div>
		  </section>
		  <!--== End Account Area Wrapper ==-->
	  

</main>
<script>
	function myFunction() {
	  var x = document.getElementById("frm_pass");
	  if (x.type === "password") {
		x.type = "text";
	  } else {
		x.type = "password";
	  }
	}
	</script>
  
{% endblock content %}

src/accounts/templates/accounts/profile.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
  Profile
{% endblock title %}
{% block content %}
  {% include "shop/header.html" %}
  <main class="main-content">
        <!--== Start Account Area Wrapper ==-->
        <section>
            <div class="container" data-padding-top="62"> 
              <h4 class="fz-24 mb-25">Your account</h4>
              <div class="row">
                <div class="col-lg-4 col-sm-6">
                  <div class="account-item">
                    <div class="account-inner mb-30">
                      <a href="#/">
                        <i class="fa fa-user-circle"></i>
                        <span>Information</span>
                      </a>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                  <div class="account-item">
                    <div class="account-inner mb-30">
                      <a href="#/">
                        <i class="fa fa-map-marker"></i>
                        <span>Add first address</span>
                      </a>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                  <div class="account-item">
                    <div class="account-inner mb-30">
                      <a href="#/">
                        <i class="fa fa-calendar"></i>
                        <span>Order history and details</span>
                      </a>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                  <div class="account-item">
                    <div class="account-inner">
                      <a href="#/">
                        <i class="fa fa-credit-card-alt"></i>
                        <span>Credit slips</span>
                      </a>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                  <div class="account-item">
                    <div class="account-inner">
                      <a href="#/">
                        <i class="fa fa-user"></i>
                        <span>GDPR - Personal data</span>
                      </a>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                  <div class="account-item">
                    <div class="account-inner">
                      <a href="#/">
                        <i class="fa fa-smile-o"></i>
                        <span>Sign out</span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <!--== End Account Area Wrapper ==-->

          {% include "shop/contact.html" %}
  </main>
  {% include "shop/footer.html" %}
{% endblock content %}

src/accounts/templates/accounts/signup.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
SignUp
  
{% endblock title %}
{% block content %}

{% include "shop/header.html" %}
<main class="main-content">
	    <!--== Start Account Area Wrapper ==-->
		<section>
			<div class="container" data-padding-top="62"> 
			  <h4 class="fz-24 mb-25">Create an account</h4>
			  <div class="row">
				<div class="col-12">
				  <div class="register-form-content">
					<div class="register-form">
					  <span class="login-account">Already have an account? <a href="{% url 'accounts:login_page' %}">Log in instead!</a></span>
					  <form action="#" method="post">
						{% csrf_token %}
						<div class="form-group row">
						  <label class="col-md-3" for="first_name">First name</label>
						  <div class="col-md-6">
							<input name="first_name" id="first_name" class="form-control" type="text">
						  </div>
						</div>
						<div class="form-group row">
						  <label class="col-md-3" for="last_name">Last name</label>
						  <div class="col-md-6">
							<input name="last_name" id="last_name" class="form-control" type="text">
						  </div>
						</div>
						<div class="form-group row">
						  <label class="col-md-3" for="email">Email</label>
						  <div class="col-md-6">
							<input name="email" id="email" class="form-control" type="email">
						  </div>
						</div>
						<div class="form-group row">
							<label class="col-md-3" for="phone_number">Phone Number</label>
							<div class="col-md-6">
							  <input name="phone_number" id="phone_number" class="form-control" type="number">
							</div>
						  </div>
						<div class="form-group row">
						  <label class="col-md-3" for="password">Password</label>
						  <div class="col-md-6">
							<div class="pass-content">
							  <input name="password" type="password" class="form-control" id="frm_pass1">
							  <span class="show-pass" onclick="myFunction('frm_pass1')">show</span>
							</div>
						  </div>
						</div>
						<div class="form-group row">
							<label class="col-md-3" for="password">Confirm Password</label>
							<div class="col-md-6">
							  <div class="pass-content">
								<input name="confirm_password" type="password" class="form-control" id="frm_pass2">
								<span class="show-pass" onclick="myFunction('frm_pass2')">show</span>
							  </div>
							</div>
						</div>
						<div class="row">
							<div class="col-12 text-end">
								<input class="btn-save" type="submit" value="SignUp">
							</div>
						  </div>
					  </form>
					</div>

					
				  </div>
				</div>
			  </div>
			</div>
		  </section>
		  <!--== End Account Area Wrapper ==-->

{% include "shop/contact.html" %}
</main>
{% include "shop/footer.html" %}

<script>
	function myFunction(inputId) {
	  var x = document.getElementById(inputId);
	  if (x.type === "password") {
		x.type = "text";
	  } else {
		x.type = "password";
	  }
	}
	</script>
  
{% endblock content %}