src/blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path('blog/', views.blog, name="blog"),
    path('blog-detail/', views.blog_detail, name="blog_detail")
]

src/cart/urls.py
from django.urls import path
from cart import views

app_name = "cart"


urlpatterns = [
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name="add_to_cart"),
    path('cart/', views.view_cart, name="view_cart"),
    path('delete-from-cart/<int:product_id>/', views.delete_cart_items, name="delete_from_cart"),
]

src/cosmetics/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include('orders.urls')),
    path('', include('accounts.urls')),
    path('', include('cart.urls')),
    path('', include('payment.urls')),
    path('', include('blog.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='initial_page'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('homepage/', views.homepage_view, name="homepage"),
    path('products/', views.products_list, name='product_list'),
    path('filter/<slug:slug>/', views.filter_by_category, name="filter_by_category"),
    path('about/', views.about, name="about"),
    path('add/wishlist/<int:product_id>/', views.add_to_wishlist, name="add_to_wishlist"),
    path('remove/wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/', views.wishlist, name="wishlist"),
    path('about/', views.about, name="about"),
    path('compare/', views.compare, name="compare"),
    path('contact/', views.contact, name="contact"),
    path('add-to-compare/<int:product_id>/', views.add_to_compare, name="add_to_compare"),
    path('remove_from_compare/<int:product_id>/', views.remove_from_compare, name="remove_from_compare"),
    path('clear_compare/', views.clear_compare, name="clear_compare")
]

src/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Post(models.Model):
    title = models.CharField(max_length=1200)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True)
    author = models.CharField(max_length=1024)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={"slug": self.slug})

    class Meta:
        db_table = 'Post'
        verbose_name = 'Post'
        verbose_name_plural = 'Post'

src/shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from PIL import Image


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)  # Call the real save() method

    class Meta:
        db_table = 'Category'
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    stock_quantity = models.PositiveIntegerField()
    image = models.ImageField(upload_to='products', null=True)
    slug = models.SlugField(unique=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)

        super(Product, self).save(*args, **kwargs)  # Call the real save() method

        img = Image.open(self.image.path)

        desired_width = 200
        desired_height = 300

        img.thumbnail((desired_width, desired_height))

        img.save(self.image.path)

    def get_absolute_url(self):
        return reverse("shop:product_detail", kwargs={"slug": self.slug})

    class Meta:
        db_table = 'Product'
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class Wishlist(models.Model):
    from accounts.models import Profile

    user = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user

    class Meta:
        db_table = 'Wishlist'
        verbose_name = 'Wishlist'
        verbose_name_plural = 'Wishlists'

src/blog/views.py
from django.http import HttpResponse
from django.shortcuts import render


def blog(request):
    return render(request, "blog/blog.html")


def blog_detail(request):
    return render(request, 'blog/blog_detail.html')

src/shop/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect

from cart.cart import CartObject
from shop.compare import Comparison
from shop.models import Category, Product, Wishlist


def paginat(request, list_objects):
    p = Paginator(list_objects, 20)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)
    return page_obj


@login_required(login_url="accounts:login_page")
def index(request):
    products = Product.objects.all()
    context = {
        'products': paginat(request, products)
    }
    return render(request, 'shop/main.html', context)

@login_required(login_url="accounts:login_page")
def homepage_view(request):
    return render(request, "shop/index.html")


def products_list(request):
    return render(request, 'shop/product_list.html')


@login_required(login_url='accounts:login_page')
def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    if request.method == 'POST':
        cart = CartObject(request)
        quantity = int(request.POST.get('quantity', 0))
        cart.add(product=product, quantity=quantity)
        return redirect('cart:view_cart')

    related_products = Product.objects.filter(category=product.category).all()[:5]
    context = {
        'product': product,
        # 'wishlist': 'wishlist',
        'related_products': related_products
    }
    # if request.user.wishlist.filter(id=product.id).first():
    #     context['wishlist'] = 'remove'

    return render(request, 'shop/product_detail.html', context)


def filter_by_category(request, slug):
    result = []
    category = Category.objects.filter(slug=slug).first()

    [
        result.append(product) \
        for product in Product.objects.filter(category=category.id).all()
    ]

    context = {
        'products': paginat(request, result)
    }
    return render(request, 'home')


@login_required(login_url='accounts:login_page')
def add_to_wishlist(request, product_id):
    user = request.user
    product = get_object_or_404(Product, id=product_id)
    wishlist = Wishlist.objects.get_or_create(user=user, product=product)

    return redirect('shop:wishlist')


@login_required(login_url='accounts:login_page')
def remove_from_wishlist(request, product_id):
    user = request.user
    product = get_object_or_404(Product, id=product_id)
    wishlist = Wishlist.objects.filter(user=user, product=product)
    wishlist.delete()

    return redirect('shop:wishlist')


@login_required(login_url='accounts:login_page')
def wishlist(request):
    user = request.user
    wishlist = Wishlist.objects.filter(user=request.user)
    context = {
        'wishlist': wishlist
    }
    return render(request, 'shop/wishlist.html', context)


def search(request):
    query = request.GET.get('q')
    products = Product.objects.filter(name__icontains=query).all()

    context = {
        'products': paginat(request, products)
    }
    return render(request, 'homepage.html', context)


def about(request):
    return HttpResponse("About Us")


def contact(request):
    return render(request, "shop/contact-us.html")


def compare(request):
    return render(request, 'shop/compare.html')

def add_to_compare(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    comparison = Comparison(request)
    comparison.add(product=product)
    comparison.save()

    return redirect('shop:compare')


def remove_from_compare(request, product_id):
    comparison = Comparison(request)
    product = get_object_or_404(Product, id=product_id)

    comparison.remove(product)
    comparison.save()

    return redirect('shop:compare')


def clear_compare(request):
    comparison = Comparison(request)
    comparison.clear()
    return redirect('shop:homepage')

src/shop/templates/shop/compare.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %} 
Compare
{% endblock title %} 
{% block content %}
  


{% include "shop/header.html" %}
<main class="main-content">
    <section class="product-area">
        <div class="container" data-padding-top="62">
          <div class="shopping-compare-wrap">
            <h4 class="title fz-24 mb-0">Products compare</h4>
            <div class="poscompare-table-container">
              <div class="poscompare-product-tr mb-30">
                <div class="poscompare-product-td">
                  <a href="{% url 'shop:clear_compare' %}" class="poscompare-remove-all">Remove all products</a>
                </div>
                {% for item in compare %}
                <div class="poscompare-product-td">
                  <div class="poscompare-product">
                    <div class="product-thumb">
                      <a href='{{item.product.get_absolute_url}}'>
                        <img src="{{item.product.image.url}}" alt="{{item.product.name}}">
                      </a>
                      <a href="{% url 'shop:remove_from_compare' item.product.id %}" class="poscompare-remove">Remove</a>
                    </div>
                    <div class="product-info">
                      <h4 class="title"><a href='{{item.product.get_absolute_url}}'>{{item.product.name}}</a></h4>
                      <div class="prices">
                        <span class="price-old visually-hidden">€{{item.product.price}}</span>
                        <span class="price text-black">€{{item.product.price}}</span>
                      </div>
                      <a class='btn-product-add' href='{% url 'cart:add_to_cart' item.product.id %}'>Add to cart</a>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
              
              <div class="poscompare-product-tr poscompare-data-list list-bg-color">
                
                <div class="poscompare-product-td">
                  <span class="title">Category</span>
                </div>
                {% for item in compare %}
                <div class="poscompare-product-td">
                  <span class="span">{{item.product.category.name}}</span>
                </div>
                {% endfor %}
              </div>
              
              <div class="poscompare-product-tr poscompare-data-list">
                <div class="poscompare-product-td">
                  <span class="title">Paper Type</span>
                </div>
                {% for item in compare %}
                <div class="poscompare-product-td">
                  <span class="span">{{item.product.category.name}}</span>
                </div>
                {% endfor %}
              </div>
              <div class="poscompare-product-tr poscompare-data-list list-bg-color">
                <div class="poscompare-product-td">
                  <span class="title">Color</span>
                </div>
                {% for item in compare %}
                <div class="poscompare-product-td">
                  <span class="span">{{item.product.category.name}}</span>
                </div>
                {% endfor %}
              </div>
              <div class="poscompare-product-tr poscompare-data-list">
                <div class="poscompare-product-td">
                  <span class="title">Size</span>
                </div>
                {% for item in compare %}
                <div class="poscompare-product-td">
                  <span class="span">{{item.product.category.name}}</span>
                </div>
                {% endfor %}
              </div>
              <div class="poscompare-product-tr poscompare-data-list list-bg-color">
                <div class="poscompare-product-td">
                  <span class="title">Frame Size</span>
                </div>
                {% for item in compare %}
                <div class="poscompare-product-td">
                  <span class="span">60x90cm</span>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </section>
</main>
{% include "shop/footer.html" %}
{% endblock content %}  

src/shop/templates/shop/product-category.html
    {% load static %}
    <!--== Start Product Category Area Wrapper ==-->
    <section class="product-area product-category-area">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 m-auto">
            <div class="section-title text-center">
              <h2 class="title">Popular Categories</h2>
              <div class="desc">
                <p>Some of our popular categories include cosmetic</p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <div class="product-categorys-col5-slider owl-carousel owl-theme">
              <div class="item">
                <div class="product-category-item">
                  <div class="inner-content">
                    <div class="thumb">
                      <img src="{% static 'shop/img/makeup.jpeg' %}" alt="Category" class="img">
                    </div>
                    <div class="content">
                      <p class="product-number">13 products</p>
                      <h4 class="title"><a href='{% url "shop:product_list" %}'>Makeup</a></h4>
                    </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="product-category-item">
                  <div class="inner-content">
                    <div class="thumb">
                      <img src="{% static 'shop/img/skincare.jpeg' %}" alt="Category class="img">
                    </div>
                    <div class="content">
                      <p class="product-number">13 products</p>
                      <h4 class="title"><a href='{% url "shop:product_list" %}'>Skin Care</a></h4>
                    </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="product-category-item">
                  <div class="inner-content">
                    <div class="thumb">
                      <img src="assets/img/shop/category/03.jpg" alt="Category" class="img">
                    </div>
                    <div class="content">
                      <p class="product-number">13 products</p>
                      <h4 class="title"><a href='{% url "shop:product_list" %}'>Health Care</a></h4>
                    </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="product-category-item">
                  <div class="inner-content">
                    <div class="thumb">
                      <img src="assets/img/shop/category/04.jpg" alt="Category" class="img">
                    </div>
                    <div class="content">
                      <p class="product-number">13 products</p>
                      <h4 class="title"><a href='{% url "shop:product_list" %}'>Makeup Tools</a></h4>
                    </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="product-category-item">
                  <div class="inner-content">
                    <div class="thumb">
                      <img src="assets/img/shop/category/01.jpg" alt="Category" class="img">
                    </div>
                    <div class="content">
                      <p class="product-number">13 products</p>
                      <h4 class="title"><a href='{% url "shop:product_list" %}'>Skin Care Tools</a></h4>
                    </div>
                  </div>
                </div>
              </div>
              <div class="item">
                <div class="product-category-item">
                  <div class="inner-content">
                    <div class="thumb">
                      <img src="assets/img/shop/category/02.jpg" alt="Category" class="img">
                    </div>
                    <div class="content">
                      <p class="product-number">13 products</p>
                      <h4 class="title"><a href='{% url "shop:product_list" %}'>Nail Art & Tools</a></h4>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--== End Product Category Area Wrapper ==-->

src/shop/templates/shop/product-slider.html
    <!--== Start Product Area Wrapper ==-->
    <section class="product-area">
      <div class="container pt-95 pt-lg-70">
        <div class="row">
          <div class="col-sm-8 m-auto">
            <div class="section-title text-center">
              <h2 class="title">New Arrivals</h2>
              <div class="desc">
                <p>Add our new arrivals to your weekly lineup</p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <div class="product-slider owl-carousel owl-theme">
              {% for product in products %}
              <div class="item">

                <!--== Start Shop Item ==-->
                <div class="product-item">
                  <div class="inner-content">
                    <div class="product-thumb">
                      <a href='{{product.get_absolute_url}}'>
                        <img src="{{product.image.url}}" alt="{{product.name}}">
                      </a>
                      <div class="product-action">
                        <div class="addto-wrap">
                          <a class='add-wishlist' href='{% url "shop:add_to_wishlist" product.id %}' title='Add to wishlist'>
                            <i class="icon-heart icon"></i>
                          </a>
                          <a class='add-compare' href='{% url "shop:add_to_compare" product.id %}' title='Add to compare'>
                            <i class="icon-shuffle icon"></i>
                          </a>
                        </div>
                      </div>
                      <ul class="product-flag">
                        <li class="new">New</li>
                        <li class="discount">-10%</li>
                      </ul>
                    </div>
                    <div class="product-desc">
                      <div class="product-info">
                        <h4 class="title"><a href='{{product.get_absolute_url}}'>{{product.name}}</a></h4>
                        <div class="prices">
                          <span class="price">{{product.price}}</span>
                        </div>
                      </div>
                      <div class="product-footer">
                        <form action="{% url 'cart:add_to_cart' product.id %}" method="post">
                          {% csrf_token %}
                          <input type="hidden" name="quantity" value="1">
                        <a  class='btn-product-add' ><button href='{% url "cart:add_to_cart" product.id %}' style="border: none; background-color: transparent;" type="submit">Add to cart</button></a>
                        </form>
                        <a class="btn-quick-view" href="javascript:;" title="Quick view">Quick view</a>
                      </div>
                    </div>
                  </div>
                </div>

                <!--== End Shop Item ==-->
              </div>
               {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </section>
    <!--== End Product Area Wrapper ==-->


    <!--== Start Product Area Wrapper ==-->
    <section class="product-area">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 m-auto">
            <div class="section-title text-center mb-30">
              <h2 class="title">Our Products</h2>
              <div class="desc">
                <p>Add our products to weekly line up</p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <div class="product-tabs-content-wrap">
              <ul class="nav mb-25 product-tab-nav" id="pills-tab" role="tablist">
                <li role="presentation">
                  <a class="active" id="makeup-tab" data-bs-toggle="pill" href="#makeup" role="tab" aria-controls="makeup" aria-selected="true">Makeup</a>
                </li>
                <li role="presentation">
                  <a id="skin-care-tab" data-bs-toggle="pill" href="#skin-care" role="tab" aria-controls="skin-care" aria-selected="false">Skin Care</a>
                </li>
                <li role="presentation">
                  <a id="health-care-tab" data-bs-toggle="pill" href="#health-care" role="tab" aria-controls="health-care" aria-selected="false">Health Care</a>
                </li>
              </ul>
              <div class="tab-content product-tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="makeup" role="tabpanel" aria-labelledby="makeup-tab">
                  <div class="row">
                    <div class="col-12">
                      <div class="product-slider owl-carousel owl-theme owl-loaded owl-drag">
                        {% for product in products %}
                        <div class="item">
                          <!--== Start Shop Item ==-->
                          <div class="product-item">
                            <div class="inner-content">
                              <div class="product-thumb">
                                <a href='{{product.get_absolute_url}}'>
                                  <img src="{{product.image.url}}" alt="{{product.name}}">
                                </a>
                                <div class="product-action">
                                  <div class="addto-wrap">
                                    <a class='add-wishlist' href='{% url "shop:add_to_wishlist" product.id %}' title='Add to wishlist'>
                                      <i class="icon-heart icon"></i>
                                    </a>
                                    <a class='add-compare' href='{% url "shop:add_to_compare" product.id %}' title='Add to compare'>
                                      <i class="icon-shuffle icon"></i>
                                    </a>
                                  </div>
                                </div>
                              </div>
                              <div class="product-desc">
                                <div class="product-info">
                                  <h4 class="title"><a href='{{ product.get_absolute_url }}'>{{product.name}}</a></h4>
                                  <div class="prices">
                                    <span class="price text-black">Ksh. {{ product.price }}</span>
                                  </div>
                                </div>
                                <div class="product-footer">
                                  <form action="{% url 'cart:add_to_cart' product.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="quantity" value="1">
                                  <a  class='btn-product-add' ><button href='{% url "cart:add_to_cart" product.id %}' style="border: none; background-color: transparent;" type="submit">Add to cart</button></a>
                                  </form>
                                  <a class="btn-quick-view" href="javascript:;" title="Quick view">Quick view</a>
                                </div>
                              </div>
                            </div>
                          </div>
                          <!--== End Shop Item ==-->
                        </div>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tab-pane fade" id="skin-care" role="tabpanel" aria-labelledby="skin-care-tab">
                  <div class="row">
                    <div class="col-12">
                      <div class="product-slider owl-carousel owl-theme">
                        {% for product in products %}
                        <div class="item">
                          <!--== Start Shop Item ==-->
                          <div class="product-item">
                            <div class="inner-content">
                              <div class="product-thumb">
                                <a href='{{product.get_absolute_url}}'>
                                  <img src="{{ product.image.url }}" alt="{{product.name}}">
                                </a>
                                <div class="product-action">
                                  <div class="addto-wrap">
                                    <a class='add-wishlist' href='{% url "shop:add_to_wishlist" product.id %}' title='Add to wishlist'>
                                      <i class="icon-heart icon"></i>
                                    </a>
                                    <a class='add-compare' href='{% url "shop:add_to_compare" product.id %}' title='Add to compare'>
                                      <i class="icon-shuffle icon"></i>
                                    </a>
                                  </div>
                                </div>
                              </div>
                              <div class="product-desc">
                                <div class="product-info">
                                  <h4 class="title"><a href='{{product.get_absolute_url}}'>{{product.name}}</a></h4>
                                  <div class="prices">
                                    <span class="price">Ksh.{{product.price}}</span>
                                  </div>
                                </div>
                                <div class="product-footer">
                                  <form action="{% url 'cart:add_to_cart' product.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="quantity" value="1">
                                  <a  class='btn-product-add' ><button href='{% url "cart:add_to_cart" product.id %}' style="border: none; background-color: transparent;" type="submit">Add to cart</button></a>
                                  </form>
                                  <a class="btn-quick-view" href="javascript:;" title="Quick view">Quick view</a>
                                </div>
                              </div>
                            </div>
                          </div>
                          <!--== End Shop Item ==-->
                        </div>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tab-pane fade" id="health-care" role="tabpanel" aria-labelledby="health-care-tab">
                  <div class="row">
                    <div class="col-12">
                      <div class="product-slider owl-carousel owl-theme">
                        {% for product in products %}
                        <div class="item">
                          <!--== Start Shop Item ==-->
                          <div class="product-item">
                            <div class="inner-content">
                              <div class="product-thumb">
                                <a href='{{product.get_absolute_url}}'>
                                  <img src="{{product.image.url}}" alt="{{product.name}}">
                                </a>
                                <div class="product-action">
                                  <div class="addto-wrap">
                                    <a class='add-wishlist' href='{% url "shop:add_to_wishlist" product.id %}' title='Add to wishlist'>
                                      <i class="icon-heart icon"></i>
                                    </a>
                                    <a class='add-compare' href='{% url "shop:add_to_compare" product.id %}' title='Add to compare'>
                                      <i class="icon-shuffle icon"></i>
                                    </a>
                                  </div>
                                </div>
                              </div>
                              <div class="product-desc">
                                <div class="product-info">
                                  <h4 class="title"><a href='{{product.get_absolute_url}}'>{{product.name}}</a></h4>
                                  <div class="prices">
                                    <span class="price">{{product.price}}</span>
                                  </div>
                                </div>
                                <div class="product-footer">
                                  <form action="{% url 'cart:add_to_cart' product.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="quantity" value="1">
                                  <a  class='btn-product-add' ><button href='{% url "cart:add_to_cart" product.id %}' style="border: none; background-color: transparent;" type="submit">Add to cart</button></a>
                                  </form>
                                  <a class="btn-quick-view" href="javascript:;" title="Quick view">Quick view</a>
                                </div>
                              </div>
                            </div>
                          </div>
                          <!--== End Shop Item ==-->
                        </div>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--== End Product Area Wrapper ==-->