src/blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path('blog/', views.blog, name="blog"),
    path('blog-detail/', views.blog_detail, name="blog_detail")
]

src/cart/urls.py
from django.urls import path
from cart import views

app_name = "cart"


urlpatterns = [
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name="add_to_cart"),
    path('cart/', views.view_cart, name="view_cart"),
    path('delete-from-cart/<int:product_id>/', views.delete_cart_items, name="delete_from_cart"),
]

src/cosmetics/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include('orders.urls')),
    path('', include('accounts.urls')),
    path('', include('cart.urls')),
    path('', include('payment.urls')),
    path('', include('blog.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/urls.py
from django.urls import path
from orders import views

app_name = "orders"


urlpatterns = [
    path('pending-orders/', views.get_pending_orders, name="pending_orders"),
    path('create-order/', views.create_order, name="create_order")
]

src/shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='initial_page'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('homepage/', views.homepage_view, name="homepage"),
    path('products/', views.products_list, name='product_list'),
    path('filter/<slug:slug>/', views.filter_by_category, name="filter_by_category"),
    path('about/', views.about, name="about"),
    path('add/wishlist/<int:product_id>/', views.add_to_wishlist, name="add_to_wishlist"),
    path('remove/wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/', views.wishlist, name="wishlist"),
    path('about/', views.about, name="about"),
    path('compare/', views.compare, name="compare"),
    path('contact/', views.contact, name="contact"),
    path('add-to-compare/<int:product_id>/', views.add_to_compare, name="add_to_compare"),
    path('remove_from_compare/<int:product_id>/', views.remove_from_compare, name="remove_from_compare"),
    path('clear_compare/', views.clear_compare, name="clear_compare")
]

src/cart/models.py
from django.contrib.sessions.models import Session

from django.db import models
from shop.models import Product
from accounts.models import Profile
from django.utils import timezone


class Cart(models.Model):
    owner = models.OneToOneField(Profile, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.owner

    def get_cart_items(self):
        return self.items.all()

    def get_total_price(self):
        total_cost = sum(item.total_price() or 0 for item in self.get_cart_items())
        return total_cost
    def __len__(self):
        return sum(item.quantity for item in self.get_cart_items())

    def get_total_dictinct_items(self):
        return self.items.count()

    class Meta:
        db_table = 'Cart'
        verbose_name = 'Cart'
        verbose_name_plural = 'Carts'


class CartItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    quantity = models.PositiveIntegerField(default=1)
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name

    def total_price(self):
        return self.product.price * self.quantity

    class Meta:
        db_table = 'CartItem'
        verbose_name = 'CartItem'
        verbose_name_plural = 'CartItems'

src/cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404

from cart.cart import CartObject
from cart.models import CartItem, Cart
from shop.models import Product


# @login_required(login_url='accounts:login_page')
# @require_POST
def add_to_cart(request, product_id):
    user = request.user
    product = get_object_or_404(Product, id=product_id)
    quantity = int(request.POST.get('quantity', 1))
    # update_quatity = int(request.POST.get('update_quantity'))
    if request.method == "POST":
        if user.is_authenticated:
            cart, created = Cart.objects.get_or_create(owner=user)

            cart_item, created = CartItem.objects.get_or_create(
                cart=cart,
                product=product,
            )
            cart_item.quantity = quantity
            # cart_item.quantity = update_quatity
            cart_item.save()
            cart.save()
        else:
            cart = CartObject(request)
            cart.add(product=product, quantity=quantity)

    return redirect('cart:view_cart')


# @login_required(login_url='accounts:login_page')
def view_cart(request):
    cart = CartObject(request)
    # for item in cart:
    #     item['update_quantity_form'] = CartAddProductForm(
    #         initial={
    #             'quantity': item['quantity'],
    #             'update': True
    #         }
    #     )

    return render(request, 'cart/cart.html')


# @login_required(login_url='accounts:login_page')
def delete_cart_items(request, product_id):
    user = request.user

    if user.is_authenticated:
        cart = Cart.objects.get(owner=user)
        cart_item = CartItem.objects.filter(cart=cart)
        cart_item.delete()
    else:
        cart = CartObject(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        messages.success(request, "Item removed from cart")
    return redirect('cart:view_cart')

src/cart/templates/cart/cart.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
Cart
{% endblock title %}

{% block content %}

{% include 'shop/header.html' %}
<main>
  <section class="product-area">
    <div class="container" data-padding-top="62">
      <div class="shopping-cart-wrap">
        {% if cart|length > 0 %}
        <div class="row">
          <div class="col-lg-8">
            <div class="shopping-cart-content">
              <h4 class="title">Shopping Cart</h4>
              {% for item in cart %}
              <p> Debug: Item in Cart</p>
              <div class="shopping-cart-item">
                <div class="row">
                  <div class="col-4 col-md-3">
                    <div class="product-thumb">
                      <img src="{{item.product.image.url}}" alt="{{item.product.name}}">
                    </div>
                  </div>
                  <div class="col-8 col-md-4">
                    <div class="product-content">
                      <h5 class="title"><a href='{{item.product.get_absolute_url}}'>{{item.product.name}}</a></h5>
                      <h6 class="product-price">{{item.product.price}}</h6>
                    </div>
                  </div>
                  <div class="col-6 offset-4 offset-md-0 col-md-5">
                    <div class="product-info">
                      <div class="row">
                        <div class="col-md-10 col-xs-6">
                          <div class="row">
                            <div class="col-md-6 col-xs-6 qty">
                              <div class="product-quick-qty">
                                <span>Quantity: </span>{{item.quantity}}
                                <form action="{% url 'cart:add_to_cart' item.product.id %}" method="post">
                                  {% csrf_token %}
                                    <div class="pro-qty">
                                      <input name="quantity" type="text" id="quantity" title="Quantity" value="1">
                                    </div>
                                  <button type="submit" class="btn-product-add">
                                    Add to cart
                                  </button>
                                </form>
                              </div>
                            </div>

                            <div class="col-md-6 col-xs-2 price">
                              <h6 class="product-price">{{item.total_price}}</h6>
                            </div>
                          </div>
                        </div>
                        <div class="col-md-2 col-xs-2 text-end">
                          <form action="" method="post">
                            {% csrf_token %}
                            <div class="product-close">

                              <a type="submit" href="{% url 'cart:delete_from_cart' item.product.id %}"><i
                                  class="fa-solid fa-trash"></i></a>

                            </div>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
              <a class="btn-primary" href="{% url 'shop:product_list' %}">Continue shopping</a>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="shopping-cart-summary mt-md-70">
              <div class="cart-detailed-totals">
                <div class="card-block">
                  <div class="card-block-item">
                    <span class="label">No of Items</span>
                    <span class="value">{{cart| length}}</span>
                  </div>
                  <div class="card-block-item">
                    <span class="label">Total price</span>
                    <span class="value">{{get_total_price}}</span>
                  </div>
                  <div class="card-block-item">
                    <span class="label">Shipping</span>
                    <span class="value">Free</span>
                  </div>
                </div>
                <div class="separator"></div>
                <div class="card-block">
                  <div class="card-block-item">
                    <span class="label">Total (Tax Incl.)</span>
                    <span class="value">{{get_total_price}}</span>
                  </div>
                </div>
                <div class="separator"></div>
              </div>
              <div class="checkout-shopping">
                <a class='btn-checkout' href="{% url 'orders:create_order' %}">Proceed to checkout</a>
              </div>
            </div>
          </div>
        </div>
        {% else %}
        <div class="col-md-8 mt-5 pt-5 text-center">
          <br>
          <h3 class="text-muted text-capitalize">cart is empty..!</h3>
          <a href="/" class="text-primary text-decoration-none">Back</a>
        </div>
        {% endif %}
      </div>
    </div>
  </section>

  {% include 'shop/contact.html' %}
</main>

{% include 'shop/footer.html' %}

{% endblock content %}